### ISSUE TITLE
strategyqa's cots from CHatGPT is more accurate than you give it  

### ISSUE THREAD

**Issue by pirongcheng** [Nardien/KARD#3]
In your paper, you mention that the accuracy of the Chain of Thought (CoT) reasoning from ChatGPT on the StrategyQA dataset is 66%. The StrategyQA training set contains 1,603 samples. If we generate 10 rationales per sample, the expected number of correct CoTs would be 1,603 × 10 × 0.66 = 10,580. However, when I ran preprocess_cot.py, I found 14,788 correct CoTs in the chatgpt_output data you provided. I’m not sure why there’s this discrepancy—could you explain it?

**Comment by Nardien** [comment]
Hi, thank you for your interest in our work!

It seems that you used the accuracy from Table 2 to calculate that number. However, please note that this accuracy represents per-problem accuracy, not per-rationale accuracy. As a result, the number of rationales filtered out may vary.

I hope this clarifies your question!

**Comment by pirongcheng** [comment]
But why is the per-rationale accuracy higher than the per-problem accuracy?
When I ran your project and generated rationales using LLMs, my per-rationale accuracy was similar to my per-problem accuracy. Additionally, when I ran preprocess_cot.py, I obtained fewer correct chains of thought (CoTs) compared to your results.
Could you please explain how you generated the rationales using LLMs?Thank you.
