### ISSUE TITLE
the per-rationale accuracy is more higher than the per-problem accuracy

### ISSUE THREAD

**Issue by pirongcheng** [Nardien/KARD#4]
But why is the per-rationale accuracy higher than the per-problem accuracy?
When I ran your project and generated rationales using LLMs, my per-rationale accuracy was similar to my per-problem accuracy. Additionally, when I ran preprocess_cot.py, I obtained fewer correct chains of thought (CoTs) compared to your results.
Could you please explain how you generated the rationales using LLMs?Thank you.

**Comment by Nardien** [comment]
Thank you for your follow-up question! One possible cause could be that we use google/flan-t5-large for rationale filtering.

For rationale generation with LLMs, we apply the prompt provided in Table 12 of the Appendix.

I hope this helps clarify your question!
