### ISSUE TITLE
Could you please share the code that generates rationales of the teacher model?

### ISSUE THREAD

**Issue by pirongcheng** [Nardien/KARD#5]
Hello, could you please share the code that generates rationales of the teacher model?It would have helped me a lot if you could, thank you very much!

**Comment by Nardien** [comment]
Hello, thank you for reaching out! Please note that the code I’ve uploaded is specific to the USMLE-MedQA dataset. You can find it here:

https://github.com/Nardien/KARD/blob/main/generate_explanations.py

I hope this helps! If you have any other questions or need further assistance, feel free to let me know.

**Comment by pirongcheng** [comment]
Thank you for your help very much!

**Comment by Nardien** [comment]
In addition, please note that this code uses openai library version 0.27.0. So, if you use the recent version, please modify the code accordingly!
